name: Commit generated code
on:
  schedule:
    # every day at 6:00 UTC (9:00 MSK)
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  Run:
    name: 'Run'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.13'

      - name: Install
        run: yarn install

      - name: Generate
        run: yarn run gen

      - name: Format
        run: yarn format

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          author: Nikita Elfimov <me@tfk.name>
          committer: Nikita Elfimov <me@tfk.name>
          commit-message: 'chore(common): generated domain'
          base: master
          branch: feat/new-domain
          delete-branch: true
          assignees: TFK70
          draft: false
          title: 'Feature: new domain'
          body: 'Created new domain'
          branch-suffix: random
