name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install
        run: yarn

      - name: Build
        run: yarn workspace @react-context/app build

      - name: Stash files from dist
        run: git add react-context/src/app/dist && git stash

      - name: Checkout to gh-pages branch
        run: git checkout gh-pages

      - name: Clear the branch
        run: rm ./*

      - name: Unstash dist
        run: git stash pop

      - name: Format structure
        run: cp -a ./dist ./

      - name: Cleanup
        run: rm -rf ./dist

      - name: Commit changes
        run: |
          git add .
          git commit -m "Release changes"
          git push
